SILVER_TABLES = [
    {
        "name": "account",
        "source": "sf_account",
        "key": "id",
        "sequence_by": ["system_modstamp", "ingested_at"],
        "delete_flag": "is_deleted",
        "columns": {
            "id": "id",
            "customer_ref": "customer_ref__c",
            "name": "name",
            "type": "type",
            "industry": "industry",
            "billing_city": "billingcity",
            "billing_state": "billingstate",
            "billing_country": "billingcountry",
            "phone": "phone",
            "website": "website",
            "annual_revenue": "CAST(annualrevenue AS DECIMAL(18,2))",
            "employee_count": "numberofemployees",
            "rating": "rating",
            "owner_id": "ownerid",
            "created_at": "createddate",
            "modified_at": "lastmodifieddate",
            "system_modstamp": "systemmodstamp",
            "is_deleted": "isdeleted",
            "ingested_at": "_ingested_at",
            "source_file": "_source_file",
        },
        "rules": {
            "valid_id": "id IS NOT NULL",
            "has_customer_ref": "customer_ref IS NOT NULL",
            "name_present": "name IS NOT NULL",
        },
    },
    {
        "name": "contact",
        "source": "sf_contact",
        "key": "id",
        "sequence_by": ["system_modstamp", "ingested_at"],
        "delete_flag": "is_deleted",
        "columns": {
            "id": "id",
            "account_id": "accountid",
            "first_name": "firstname",
            "last_name": "lastname",
            "full_name": "name",
            "email": "email",
            "phone": "phone",
            "mobile_phone": "mobilephone",
            "title": "title",
            "department": "department",
            "lead_source": "leadsource",
            "mailing_city": "mailingcity",
            "mailing_state": "mailingstate",
            "mailing_country": "mailingcountry",
            "birth_date": "CAST(birthdate AS DATE)",
            "owner_id": "ownerid",
            "created_at": "createddate",
            "modified_at": "lastmodifieddate",
            "system_modstamp": "systemmodstamp",
            "is_deleted": "isdeleted",
            "ingested_at": "_ingested_at",
            "source_file": "_source_file",
        },
        "rules": {
            "valid_id": "id IS NOT NULL",
            "has_account": "account_id IS NOT NULL",
            "last_name_present": "last_name IS NOT NULL",
            "email_format": "email IS NULL OR email RLIKE '^[^@ ]+@[^@ ]+[.][^@ ]+$'",
        },
    },
    {
        "name": "support_case",
        "source": "sf_case",
        "key": "id",
        "sequence_by": ["system_modstamp", "ingested_at"],
        "delete_flag": "is_deleted",
        "columns": {
            "id": "id",
            "case_number": "casenumber",
            "account_id": "accountid",
            "contact_id": "contactid",
            "subject": "subject",
            "status": "status",
            "priority": "priority",
            "origin": "origin",
            "type": "type",
            "reason": "reason",
            "description": "description",
            "is_closed": "isclosed",
            "closed_at": "closeddate",
            "is_escalated": "isescalated",
            "owner_id": "ownerid",
            "created_at": "createddate",
            "modified_at": "lastmodifieddate",
            "system_modstamp": "systemmodstamp",
            "is_deleted": "isdeleted",
            "ingested_at": "_ingested_at",
            "source_file": "_source_file",
        },
        "rules": {
            "valid_id": "id IS NOT NULL",
            "has_account": "account_id IS NOT NULL",
            "status_known": "status IN ('New', 'Working', 'Escalated', 'Closed')",
            "priority_known": "priority IS NULL OR priority IN ('High', 'Medium', 'Low')",
        },
    },
    {
        "name": "usage_event",
        "source": "blob_usage",
        "key": "usage_id",
        "sequence_by": ["ingested_at", "source_file"],
        "delete_flag": None,
        "columns": {
            "usage_id": "usage_id",
            "customer_ref": "customer_ref",
            "usage_date": "TRY_CAST(usage_date AS DATE)",
            "service": "service",
            "units": "TRY_CAST(units AS INT)",
            "amount_aud": "TRY_CAST(amount_aud AS DECIMAL(12,2))",
            "payment_bank": "payment_bank",
            "ingested_at": "_ingested_at",
            "source_file": "_source_file",
        },
        "rules": {
            "valid_usage_id": "usage_id IS NOT NULL",
            "has_customer_ref": "customer_ref IS NOT NULL",
            "valid_date": "usage_date IS NOT NULL",
            "units_positive": "units > 0",
            "amount_non_negative": "amount_aud >= 0",
            "known_service": "service IN ('storage', 'compute', 'support', 'licensing')",
        },
    },
    {
        "name": "account_contract",
        "source": "sql_account_contracts",
        "key": "contract_id",
        "sequence_by": ["modified_at", "ingested_at"],
        "delete_flag": None,
        "columns": {
            "contract_id": "contract_id",
            "customer_ref": "customer_ref",
            "contract_tier": "contract_tier",
            "committed_monthly_aud": "TRY_CAST(committed_monthly_aud AS DECIMAL(12,2))",
            "contract_start": "TRY_CAST(contract_start AS DATE)",
            "contract_end": "TRY_CAST(contract_end AS DATE)",
            "modified_at": "TRY_CAST(modified_at AS TIMESTAMP)",
            "ingested_at": "_ingested_at",
            "source_file": "_source_file",
        },
        "rules": {
            "valid_contract_id": "contract_id IS NOT NULL",
            "has_customer_ref": "customer_ref IS NOT NULL",
            "known_tier": "contract_tier IN ('Bronze', 'Silver', 'Gold', 'Platinum')",
            "commitment_positive": "committed_monthly_aud > 0",
            "valid_start": "contract_start IS NOT NULL",
            "valid_modified_at": "modified_at IS NOT NULL",
            "end_after_start": "contract_end IS NULL OR contract_end >= contract_start",
        },
    },    
]